import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Components from '@/components'
import "./globals.css";

const inter = Lato({ 
  style: "normal",
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Natours | Exciting Tours for adventurours people",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="md:text-[50%] lg:text-[56%] xl:text-[75%]">
      <body className={`md:p-[3.7rem] ${inter.className}`}>
        <Components.Nav />
        <Components.Header />
        {children}
        <Components.Footer />
      </body>
    </html>
  );
}
